language: python

# python version
python:
  - "3.6.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run --source=app.api.v1 -m pytest app/tests/v1 && coverage report
  - coveralls

# Post coverage results to coverage.io
after-success:
  - coveralls